/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { VoteEvenOrOdd } from "./VoteEvenOrOdd";
export type { Token } from "./Token";

export { VoteEvenOrOdd__factory } from "./factories/VoteEvenOrOdd__factory";
export { Token__factory } from "./factories/Token__factory";
